server:
  port: 3001
  servlet:
    context-path: /wgcloud-agent
spring:
  application:
    name: wgcloud-agent
#日志文件输出路径
logging:
  file:
    path: ./log

#自定义配置参数
base:
  #wgcloud-server端访问地址
  serverUrl: http://172.26.24.52:3000
  #本机ip，不要用localhost或127.0.0.1
  bindIp: 172.26.24.52
  #通信token，请和server端配置的wgToken保持一致
  wgToken: wgcloud